import {createServer} from "node:http";
import {readFile,stat} from "node:fs/promises";
import {extname,join,normalize} from "node:path";
import {fileURLToPath} from "node:url";
const root=fileURLToPath(new URL(".",import.meta.url)),port=Number(process.env.PORT||3000),MAX=32000;
const mime={".html":"text/html; charset=utf-8",".js":"text/javascript; charset=utf-8",".css":"text/css; charset=utf-8",".json":"application/json; charset=utf-8",".png":"image/png",".pdf":"application/pdf",".ico":"image/x-icon"};
function json(res,s,p){res.writeHead(s,{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"});res.end(JSON.stringify(p))}
async function readBody(req){let s="";for await(const c of req){s+=c;if(s.length>MAX)throw Error("Request too large")}try{return JSON.parse(s||"{}")}catch{throw Error("Invalid JSON")}}
function demo(q){return "AI is not configured. Set AI_PROVIDER and the matching server-side API key before using the Study Assistant."}
function openaiText(d){if(d.output_text)return d.output_text;return(d.output||[]).flatMap(x=>x.content||[]).filter(x=>x.type==="output_text").map(x=>x.text||"").join("\n")||"No text returned."}
async function openai(q){const model=process.env.OPENAI_MODEL||"gpt-5-mini",instruction="You are TIT&S Study Assistant for B.Tech students at Technological Institute of Textile Sciences, Bhiwani. Answer engineering questions accurately and clearly. Prefer simple language, headings, points, examples, formulas and exam-ready structure. Do not claim sample notes are official TIT&S material.";const r=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+process.env.OPENAI_API_KEY},body:JSON.stringify({model,instructions:instruction,input:q,store:false})}),d=await r.json();if(!r.ok)throw Error(d.error?.message||"OpenAI failed");return openaiText(d)}
async function gemini(q){const model=process.env.GEMINI_MODEL||"gemini-2.0-flash",r=await fetch("https://generativelanguage.googleapis.com/v1beta/models/"+encodeURIComponent(model)+":generateContent",{method:"POST",headers:{"Content-Type":"application/json","x-goog-api-key":process.env.GEMINI_API_KEY},body:JSON.stringify({systemInstruction:{parts:[{text:"You are TIT&S Study Assistant for B.Tech students at Technological Institute of Textile Sciences, Bhiwani. Explain engineering topics accurately in simple student-friendly language. Use headings, points, examples and exam-oriented structure. Never claim sample notes are official TIT&S material."}]},contents:[{role:"user",parts:[{text:q}]}]})}),d=await r.json();if(!r.ok)throw Error(d.error?.message||"Gemini failed");return d.candidates?.[0]?.content?.parts?.map(x=>x.text||"").join("\n")||"No text returned."}
async function ai(req,res){try{const b=await readBody(req),q=b.question;if(typeof q!=="string"||q.trim().length<2||q.length>5000)return json(res,400,{error:"Question must be 2-5000 characters."});const p=(process.env.AI_PROVIDER||"").toLowerCase();if(p==="openai"&&process.env.OPENAI_API_KEY)return json(res,200,{answer:await openai(q.trim()),provider:"openai",demo:false,configured:true});if(p==="gemini"&&process.env.GEMINI_API_KEY)return json(res,200,{answer:await gemini(q.trim()),provider:"gemini",demo:false,configured:true});return json(res,503,{error:"AI is not configured. Set AI_PROVIDER and the matching server-side API key in Render environment variables."})}catch(e){console.error(e);return json(res,502,{error:"AI service unavailable. Check provider settings."})}}
async function staticFile(req,res){const path=req.url==="/"?"index.html":req.url.split("?")[0].replace(/^\/+/, "");const safe=normalize(join(root,path));if(!safe.startsWith(root))return json(res,403,{error:"Forbidden"});try{const info=await stat(safe);if(!info.isFile())throw Error();const data=await readFile(safe);res.writeHead(200,{"Content-Type":mime[extname(safe)]||"application/octet-stream","X-Content-Type-Options":"nosniff"});res.end(data)}catch{if(extname(path))return json(res,404,{error:"Not found"});const data=await readFile(join(root,"index.html"));res.writeHead(200,{"Content-Type":mime[".html"]});res.end(data)}}
createServer(async(req,res)=>{res.setHeader("X-Frame-Options","DENY");res.setHeader("Referrer-Policy","strict-origin-when-cross-origin");res.setHeader("Content-Security-Policy","default-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src https://fonts.gstatic.com; script-src 'self' 'unsafe-inline'; connect-src 'self' https://api.openai.com https://generativelanguage.googleapis.com; img-src 'self' data:;");if(req.method==="GET"&&req.url==="/api/health")return json(res,200,{ok:true,configured:Boolean((process.env.AI_PROVIDER==="openai"&&process.env.OPENAI_API_KEY)||(process.env.AI_PROVIDER==="gemini"&&process.env.GEMINI_API_KEY)),provider:process.env.AI_PROVIDER||"demo"});if(req.method==="POST"&&req.url==="/api/ai")return ai(req,res);if(req.method==="GET"||req.method==="HEAD")return staticFile(req,res);return json(res,405,{error:"Method not allowed"})}).listen(port,()=>console.log("TIT&S Notes running on "+port));