import {createServer} from "node:http";
import {readFile,stat,writeFile,mkdir,unlink} from "node:fs/promises";
import {extname,join,normalize} from "node:path";
import {fileURLToPath} from "node:url";
import {randomBytes,createHmac,scryptSync,timingSafeEqual} from "node:crypto";
const root=fileURLToPath(new URL(".",import.meta.url)),port=Number(process.env.PORT||3000),MAX=15*1024*1024,SESSION_SECRET=process.env.SESSION_SECRET||"";
const mime={".html":"text/html; charset=utf-8",".js":"text/javascript; charset=utf-8",".css":"text/css; charset=utf-8",".json":"application/json; charset=utf-8",".png":"image/png",".pdf":"application/pdf",".ico":"image/x-icon",".doc":"application/msword",".docx":"application/vnd.openxmlformats-officedocument.wordprocessingml.document",".txt":"text/plain"};
function json(res,s,p){res.writeHead(s,{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"});res.end(JSON.stringify(p))}
async function readBody(req){let s="";for await(const c of req){s+=c;if(s.length>MAX)throw Error("Request too large")}try{return JSON.parse(s||"{}")}catch{throw Error("Invalid JSON")}}
function openaiText(d){if(d.output_text)return d.output_text;return(d.output||[]).flatMap(x=>x.content||[]).filter(x=>x.type==="output_text").map(x=>x.text||"").join("\n")||"No text returned."}
async function openai(q){const model=process.env.OPENAI_MODEL||"gpt-5-mini",instruction="You are TIT&S Study Assistant for B.Tech students at Technological Institute of Textile Sciences, Bhiwani. Answer engineering questions accurately and clearly. Prefer simple language, headings, points, examples, formulas and exam-ready structure. Do not claim sample notes are official TIT&S material.";const r=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+process.env.OPENAI_API_KEY},body:JSON.stringify({model,instructions:instruction,input:q,store:false})}),d=await r.json();if(!r.ok)throw Error(d.error?.message||"OpenAI failed");return openaiText(d)}
async function gemini(q){const model=process.env.GEMINI_MODEL||"gemini-2.0-flash",r=await fetch("https://generativelanguage.googleapis.com/v1beta/models/"+encodeURIComponent(model)+":generateContent",{method:"POST",headers:{"Content-Type":"application/json","x-goog-api-key":process.env.GEMINI_API_KEY},body:JSON.stringify({systemInstruction:{parts:[{text:"You are TIT&S Study Assistant for B.Tech students at Technological Institute of Textile Sciences, Bhiwani. Answer like a patient college teacher and exam-preparation assistant. Start with a direct definition or answer, then use clear headings, short paragraphs and numbered/bulleted points. For theory questions include: meaning/definition, detailed explanation, key points, an easy example, and an exam-ready summary. For differences use a simple table when useful. For algorithms include steps/pseudocode idea and time/space complexity where relevant. For numerical or technical questions show the reasoning step by step. Match the requested depth: short for short questions, detailed for 5/10/15-mark questions. Avoid filler, repeated conclusions and overly long introductions. Use simple student-friendly English. Never claim sample notes are official TIT&S material."}]},contents:[{role:"user",parts:[{text:q}]}]})}),d=await r.json();if(!r.ok)throw Error(d.error?.message||"Gemini failed");return d.candidates?.[0]?.content?.parts?.map(x=>x.text||"").join("\n")||"No text returned."}

function cookies(req){return Object.fromEntries((req.headers.cookie||"").split(";").filter(Boolean).map(x=>{const i=x.indexOf("=");return[i<0?x:x.slice(0,i).trim(),decodeURIComponent(i<0?"":x.slice(i+1).trim())]}))}
function sign(v){return createHmac("sha256",SESSION_SECRET).update(v).digest("base64url")}
function sessionFor(role,email){if(!SESSION_SECRET)return null;const p=Buffer.from(JSON.stringify({role,email,exp:Date.now()+604800000})).toString("base64url");return p+"."+sign(p)}
function currentUser(req){const t=cookies(req).tits_session;if(!t||!SESSION_SECRET)return null;const [p,s]=t.split(".");if(!p||!s||sign(p)!==s)return null;try{const u=JSON.parse(Buffer.from(p,"base64url").toString("utf8"));return u.exp>Date.now()?u:null}catch{return null}}
function passwordMatches(password,configured){if(!configured)return false;try{const [saltHex,hashHex]=configured.split("$");if(hashHex){const expected=Buffer.from(hashHex,"hex"),actual=scryptSync(password,Buffer.from(saltHex,"hex"),expected.length);return expected.length===actual.length&&timingSafeEqual(actual,expected)}}catch{}return password===configured}
function configuredLogin(email,password,envEmail,envPassword){return Boolean(envEmail&&envPassword&&email.toLowerCase()===String(envEmail).trim().toLowerCase()&&passwordMatches(password,envPassword))}
function adminAccounts(){const pairs=[["ADMIN_EMAIL_1","ADMIN_PASSWORD_1"],["ADMIN_EMAIL_2","ADMIN_PASSWORD_2"]];return pairs.map(([e,p])=>({email:process.env[e],password:process.env[p]})).filter(x=>x.email&&x.password)}
function studentAccounts(){try{const a=JSON.parse(process.env.STUDENT_ACCOUNTS||"[]");return Array.isArray(a)?a.filter(x=>x&&x.email&&x.password):[]}catch{return []}}
function authRequired(req,res,role){const u=currentUser(req);if(!u){json(res,401,{error:"Login required."});return null}if(role&&u.role!==role){json(res,403,{error:"Admin access required."});return null}return u}
async function authLogin(req,res){try{const b=await readBody(req),email=String(b.email||"").trim(),password=String(b.password||"");let role=null;const admins=adminAccounts();const students=studentAccounts();if(admins.some(a=>configuredLogin(email,password,a.email,a.password)))role="admin";else if(students.some(a=>configuredLogin(email,password,a.email,a.password)))role="student";else return json(res,401,{error:"Invalid login details."});const token=sessionFor(role,email);if(!token)return json(res,503,{error:"Authentication is not configured. Add SESSION_SECRET in Render."});return json(res,200,{ok:true,user:{email,role}},{"Set-Cookie":"tits_session="+encodeURIComponent(token)+"; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=604800"})}catch{return json(res,400,{error:"Invalid login request."})}}
function authLogout(req,res){return json(res,200,{ok:true},{"Set-Cookie":"tits_session=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0"})}
function authMe(req,res){const u=currentUser(req);return json(res,200,{authenticated:Boolean(u),user:u?{email:u.email,role:u.role}:null})}

async function upload(req,res){const u=authRequired(req,res,"admin");if(!u)return;try{const b=await readBody(req),name=String(b.name||"").trim(),data=String(b.data||"");if(!name||!data)return json(res,400,{error:"File and metadata are required."});const allowed=/\.(pdf|doc|docx|txt)$/i;if(!allowed.test(name))return json(res,400,{error:"Only PDF, DOC, DOCX and TXT files are allowed."});const raw=Buffer.from(data,"base64");if(raw.length>10*1024*1024)return json(res,400,{error:"File is larger than 10 MB."});const dir=join(root,"uploads");await mkdir(dir,{recursive:true});const safe=name.replace(/[^a-zA-Z0-9._-]/g,"_");const stored=Date.now()+"-"+safe;await writeFile(join(dir,stored),raw);let list=[];try{list=JSON.parse(await readFile(join(dir,"index.json"),"utf8"))}catch{}const note={id:Date.now(),uploadedBy:u.email,title:String(b.title||name).slice(0,160),subject:String(b.subject||"General").slice(0,120),branch:String(b.branch||"").slice(0,40),semester:String(b.semester||"").slice(0,10),type:String(b.type||"Notes").slice(0,30),unit:String(b.unit||"").slice(0,60),description:String(b.description||"").slice(0,500),name,stored,createdAt:new Date().toISOString()};list.push(note);await writeFile(join(dir,"index.json"),JSON.stringify(list,null,2));return json(res,201,{ok:true,note})}catch(e){console.error(e);return json(res,500,{error:"Upload failed. Check server storage."})}}
async function deleteUpload(req,res){const u=authRequired(req,res,"admin");if(!u)return;try{const b=await readBody(req),id=Number(b.id);let list=[];try{list=JSON.parse(await readFile(join(root,"uploads","index.json"),"utf8"))}catch{}const n=list.find(x=>x.id===id);if(!n)return json(res,404,{error:"Resource not found."});if(n.stored)try{await unlink(join(root,"uploads",n.stored))}catch{}list=list.filter(x=>x.id!==id);await writeFile(join(root,"uploads","index.json"),JSON.stringify(list,null,2));return json(res,200,{ok:true})}catch{return json(res,500,{error:"Delete failed."})}}
async function uploads(req,res){try{const list=JSON.parse(await readFile(join(root,"uploads","index.json"),"utf8"));return json(res,200,{ok:true,notes:list})}catch{return json(res,200,{ok:true,notes:[]})}}
async function ai(req,res){try{const b=await readBody(req),q=b.question;if(typeof q!=="string"||q.trim().length<2||q.length>5000)return json(res,400,{error:"Question must be 2-5000 characters."});const p=(process.env.AI_PROVIDER||"").toLowerCase();if(p==="openai"&&process.env.OPENAI_API_KEY)return json(res,200,{answer:await openai(q.trim()),provider:"openai",demo:false,configured:true});if(p==="gemini"&&process.env.GEMINI_API_KEY)return json(res,200,{answer:await gemini(q.trim()),provider:"gemini",demo:false,configured:true});return json(res,503,{error:"Live AI is not connected yet. Add a valid OPENAI_API_KEY (or GEMINI_API_KEY) to this Render service."})}catch(e){console.error(e);return json(res,502,{error:"AI service unavailable. Check provider settings."})}}
async function staticFile(req,res){const path=req.url==="/"?"index.html":req.url.split("?")[0].replace(/^\/+/, "");const safe=normalize(join(root,path));if(!safe.startsWith(root))return json(res,403,{error:"Forbidden"});try{const info=await stat(safe);if(!info.isFile())throw Error();const data=await readFile(safe);res.writeHead(200,{"Content-Type":mime[extname(safe)]||"application/octet-stream","X-Content-Type-Options":"nosniff"});res.end(data)}catch{if(extname(path))return json(res,404,{error:"Not found"});const data=await readFile(join(root,"index.html"));res.writeHead(200,{"Content-Type":mime[".html"]});res.end(data)}}
createServer(async(req,res)=>{res.setHeader("X-Frame-Options","DENY");res.setHeader("Referrer-Policy","strict-origin-when-cross-origin");res.setHeader("Content-Security-Policy","default-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src https://fonts.gstatic.com; script-src 'self' 'unsafe-inline'; connect-src 'self' https://api.openai.com https://generativelanguage.googleapis.com; img-src 'self' data:;");if(req.method==="GET"&&req.url==="/api/health")return json(res,200,{ok:true,configured:Boolean((process.env.AI_PROVIDER==="openai"&&process.env.OPENAI_API_KEY)||(process.env.AI_PROVIDER==="gemini"&&process.env.GEMINI_API_KEY)),provider:process.env.AI_PROVIDER||"none",authConfigured:Boolean(SESSION_SECRET&&adminAccounts().length===2)});if(req.method==="GET"&&req.url==="/api/auth/me")return authMe(req,res);if(req.method==="POST"&&req.url==="/api/auth/login")return authLogin(req,res);if(req.method==="POST"&&req.url==="/api/auth/logout")return authLogout(req,res);if(req.method==="POST"&&req.url==="/api/ai")return ai(req,res);if(req.method==="POST"&&req.url==="/api/uploads")return upload(req,res);if(req.method==="DELETE"&&req.url==="/api/uploads")return deleteUpload(req,res);if(req.method==="GET"&&req.url==="/api/uploads")return uploads(req,res);if(req.method==="GET"||req.method==="HEAD")return staticFile(req,res);return json(res,405,{error:"Method not allowed"})}).listen(port,()=>console.log("TIT&S Notes running on "+port));